name-template: 'EQ-1 Network v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
commitish: dev
categories:
    - title: 'ğŸ†• ìƒˆë¡œìš´ ê¸°ëŠ¥ì´ ì¶”ê°€ë˜ì—ˆì–´ìš”!'
      labels: 'feature'
    - title: 'ğŸ ìì˜í•œ ë²„ê·¸ë¥¼ ìˆ˜ì •í–ˆìŠµë‹ˆë‹¤.'
      labels: 'bug'
    - title: 'ğŸ«¶ğŸ» ì•± ì‚¬ìš©ì„± ê°œì„ ì— í˜ì¼ìŠµë‹ˆë‹¤.'
      labels: 'improvement'
    - title: 'ğŸ› ï¸ ë” ë‚˜ì€ ì½”ë“œë¥¼ ìœ„í•´ ë…¸ë ¥í•˜ê³  ìˆìŠµë‹ˆë‹¤.'
      labels: 'refactoring'
    - title: 'ğŸ“„ í”„ë¡œì íŠ¸ì— ëŒ€í•œ ìƒì„¸ ìë£ŒëŠ” ì•„ë˜ë¥¼ ì°¸ì¡°í•˜ì„¸ìš”.'
      labels: 'documentation'
    - title: Others
      labels: '*'
change-template: '* $TITLE (#$NUMBER) by @$AUTHOR'
change-title-escapes: '\<*_&#@`'
exclude-labels:
  - 'duplicate'
  - 'good first issue'
  - 'help wanted'
  - 'invalid'
  - 'wontfix'
  - 'question'
version-resolver:
  major:
    labels:
      - 'Major'
  minor:
    labels:
      - 'Minor'
  patch:
    labels:
      - 'Patch'
  default: patch
template: |
  $CHANGES